// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test2.proto

package com.example.bigquerystorage;

public final class TestProto2 {
  private TestProto2() {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface Test2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:bigquerystorage.Test2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 age = 1;</code>
     * 
     * @return Whether the age field is set.
     */
    boolean hasAge();

    /**
     * <code>optional int32 age = 1;</code>
     * 
     * @return The age.
     */
    int getAge();

    /**
     * <code>optional int32 id = 2;</code>
     * 
     * @return Whether the id field is set.
     */
    boolean hasId();

    /**
     * <code>optional int32 id = 2;</code>
     * 
     * @return The id.
     */
    int getId();

    /**
     * <code>optional bool end_transaction = 3;</code>
     * 
     * @return Whether the endTransaction field is set.
     */
    boolean hasEndTransaction();

    /**
     * <code>optional bool end_transaction = 3;</code>
     * 
     * @return The endTransaction.
     */
    boolean getEndTransaction();

    /**
     * <code>optional int64 source_record_id = 4;</code>
     * 
     * @return Whether the sourceRecordId field is set.
     */
    boolean hasSourceRecordId();

    /**
     * <code>optional int64 source_record_id = 4;</code>
     * 
     * @return The sourceRecordId.
     */
    long getSourceRecordId();

    /**
     * <code>optional string service_file_id = 5;</code>
     * 
     * @return Whether the serviceFileId field is set.
     */
    boolean hasServiceFileId();

    /**
     * <code>optional string service_file_id = 5;</code>
     * 
     * @return The serviceFileId.
     */
    java.lang.String getServiceFileId();

    /**
     * <code>optional string service_file_id = 5;</code>
     * 
     * @return The bytes for serviceFileId.
     */
    com.google.protobuf.ByteString getServiceFileIdBytes();

    /**
     * <code>optional string name_st = 6;</code>
     * 
     * @return Whether the nameSt field is set.
     */
    boolean hasNameSt();

    /**
     * <code>optional string name_st = 6;</code>
     * 
     * @return The nameSt.
     */
    java.lang.String getNameSt();

    /**
     * <code>optional string name_st = 6;</code>
     * 
     * @return The bytes for nameSt.
     */
    com.google.protobuf.ByteString getNameStBytes();
  }

  /**
   * Protobuf type {@code bigquerystorage.Test2}
   */
  public static final class Test2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bigquerystorage.Test2)
      Test2OrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Test2.newBuilder() to construct.
    private Test2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Test2() {
      serviceFileId_ = "";
      nameSt_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({ "unused" })
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Test2();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.example.bigquerystorage.TestProto2.internal_static_bigquerystorage_Test2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return com.example.bigquerystorage.TestProto2.internal_static_bigquerystorage_Test2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.bigquerystorage.TestProto2.Test2.class,
              com.example.bigquerystorage.TestProto2.Test2.Builder.class);
    }

    private int bitField0_;
    public static final int AGE_FIELD_NUMBER = 1;
    private int age_ = 0;

    /**
     * <code>optional int32 age = 1;</code>
     * 
     * @return Whether the age field is set.
     */
    @java.lang.Override
    public boolean hasAge() {
      return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>optional int32 age = 1;</code>
     * 
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_ = 0;

    /**
     * <code>optional int32 id = 2;</code>
     * 
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>optional int32 id = 2;</code>
     * 
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int END_TRANSACTION_FIELD_NUMBER = 3;
    private boolean endTransaction_ = false;

    /**
     * <code>optional bool end_transaction = 3;</code>
     * 
     * @return Whether the endTransaction field is set.
     */
    @java.lang.Override
    public boolean hasEndTransaction() {
      return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     * <code>optional bool end_transaction = 3;</code>
     * 
     * @return The endTransaction.
     */
    @java.lang.Override
    public boolean getEndTransaction() {
      return endTransaction_;
    }

    public static final int SOURCE_RECORD_ID_FIELD_NUMBER = 4;
    private long sourceRecordId_ = 0L;

    /**
     * <code>optional int64 source_record_id = 4;</code>
     * 
     * @return Whether the sourceRecordId field is set.
     */
    @java.lang.Override
    public boolean hasSourceRecordId() {
      return ((bitField0_ & 0x00000008) != 0);
    }

    /**
     * <code>optional int64 source_record_id = 4;</code>
     * 
     * @return The sourceRecordId.
     */
    @java.lang.Override
    public long getSourceRecordId() {
      return sourceRecordId_;
    }

    public static final int SERVICE_FILE_ID_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object serviceFileId_ = "";

    /**
     * <code>optional string service_file_id = 5;</code>
     * 
     * @return Whether the serviceFileId field is set.
     */
    @java.lang.Override
    public boolean hasServiceFileId() {
      return ((bitField0_ & 0x00000010) != 0);
    }

    /**
     * <code>optional string service_file_id = 5;</code>
     * 
     * @return The serviceFileId.
     */
    @java.lang.Override
    public java.lang.String getServiceFileId() {
      java.lang.Object ref = serviceFileId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceFileId_ = s;
        }
        return s;
      }
    }

    /**
     * <code>optional string service_file_id = 5;</code>
     * 
     * @return The bytes for serviceFileId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getServiceFileIdBytes() {
      java.lang.Object ref = serviceFileId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        serviceFileId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_ST_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nameSt_ = "";

    /**
     * <code>optional string name_st = 6;</code>
     * 
     * @return Whether the nameSt field is set.
     */
    @java.lang.Override
    public boolean hasNameSt() {
      return ((bitField0_ & 0x00000020) != 0);
    }

    /**
     * <code>optional string name_st = 6;</code>
     * 
     * @return The nameSt.
     */
    @java.lang.Override
    public java.lang.String getNameSt() {
      java.lang.Object ref = nameSt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nameSt_ = s;
        }
        return s;
      }
    }

    /**
     * <code>optional string name_st = 6;</code>
     * 
     * @return The bytes for nameSt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNameStBytes() {
      java.lang.Object ref = nameSt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        nameSt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, age_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBool(3, endTransaction_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt64(4, sourceRecordId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, serviceFileId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, nameSt_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, age_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(3, endTransaction_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(4, sourceRecordId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, serviceFileId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, nameSt_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.example.bigquerystorage.TestProto2.Test2)) {
        return super.equals(obj);
      }
      com.example.bigquerystorage.TestProto2.Test2 other = (com.example.bigquerystorage.TestProto2.Test2) obj;

      if (hasAge() != other.hasAge())
        return false;
      if (hasAge()) {
        if (getAge() != other.getAge())
          return false;
      }
      if (hasId() != other.hasId())
        return false;
      if (hasId()) {
        if (getId() != other.getId())
          return false;
      }
      if (hasEndTransaction() != other.hasEndTransaction())
        return false;
      if (hasEndTransaction()) {
        if (getEndTransaction() != other.getEndTransaction())
          return false;
      }
      if (hasSourceRecordId() != other.hasSourceRecordId())
        return false;
      if (hasSourceRecordId()) {
        if (getSourceRecordId() != other.getSourceRecordId())
          return false;
      }
      if (hasServiceFileId() != other.hasServiceFileId())
        return false;
      if (hasServiceFileId()) {
        if (!getServiceFileId()
            .equals(other.getServiceFileId()))
          return false;
      }
      if (hasNameSt() != other.hasNameSt())
        return false;
      if (hasNameSt()) {
        if (!getNameSt()
            .equals(other.getNameSt()))
          return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields()))
        return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasEndTransaction()) {
        hash = (37 * hash) + END_TRANSACTION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getEndTransaction());
      }
      if (hasSourceRecordId()) {
        hash = (37 * hash) + SOURCE_RECORD_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSourceRecordId());
      }
      if (hasServiceFileId()) {
        hash = (37 * hash) + SERVICE_FILE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getServiceFileId().hashCode();
      }
      if (hasNameSt()) {
        hash = (37 * hash) + NAME_ST_FIELD_NUMBER;
        hash = (53 * hash) + getNameSt().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.bigquerystorage.TestProto2.Test2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.example.bigquerystorage.TestProto2.Test2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.example.bigquerystorage.TestProto2.Test2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.example.bigquerystorage.TestProto2.Test2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.example.bigquerystorage.TestProto2.Test2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.example.bigquerystorage.TestProto2.Test2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.example.bigquerystorage.TestProto2.Test2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static com.example.bigquerystorage.TestProto2.Test2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.bigquerystorage.TestProto2.Test2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.bigquerystorage.TestProto2.Test2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.bigquerystorage.TestProto2.Test2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static com.example.bigquerystorage.TestProto2.Test2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.example.bigquerystorage.TestProto2.Test2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder()
          : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code bigquerystorage.Test2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bigquerystorage.Test2)
        com.example.bigquerystorage.TestProto2.Test2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.example.bigquerystorage.TestProto2.internal_static_bigquerystorage_Test2_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.example.bigquerystorage.TestProto2.internal_static_bigquerystorage_Test2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.bigquerystorage.TestProto2.Test2.class,
                com.example.bigquerystorage.TestProto2.Test2.Builder.class);
      }

      // Construct using com.example.bigquerystorage.TestProto2.Test2.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        age_ = 0;
        id_ = 0;
        endTransaction_ = false;
        sourceRecordId_ = 0L;
        serviceFileId_ = "";
        nameSt_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.example.bigquerystorage.TestProto2.internal_static_bigquerystorage_Test2_descriptor;
      }

      @java.lang.Override
      public com.example.bigquerystorage.TestProto2.Test2 getDefaultInstanceForType() {
        return com.example.bigquerystorage.TestProto2.Test2.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.bigquerystorage.TestProto2.Test2 build() {
        com.example.bigquerystorage.TestProto2.Test2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.bigquerystorage.TestProto2.Test2 buildPartial() {
        com.example.bigquerystorage.TestProto2.Test2 result = new com.example.bigquerystorage.TestProto2.Test2(this);
        if (bitField0_ != 0) {
          buildPartial0(result);
        }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.bigquerystorage.TestProto2.Test2 result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.age_ = age_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.endTransaction_ = endTransaction_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.sourceRecordId_ = sourceRecordId_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.serviceFileId_ = serviceFileId_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.nameSt_ = nameSt_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.bigquerystorage.TestProto2.Test2) {
          return mergeFrom((com.example.bigquerystorage.TestProto2.Test2) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.bigquerystorage.TestProto2.Test2 other) {
        if (other == com.example.bigquerystorage.TestProto2.Test2.getDefaultInstance())
          return this;
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasEndTransaction()) {
          setEndTransaction(other.getEndTransaction());
        }
        if (other.hasSourceRecordId()) {
          setSourceRecordId(other.getSourceRecordId());
        }
        if (other.hasServiceFileId()) {
          serviceFileId_ = other.serviceFileId_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasNameSt()) {
          nameSt_ = other.nameSt_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                age_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                endTransaction_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                sourceRecordId_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                serviceFileId_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                nameSt_ = input.readBytes();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int bitField0_;

      private int age_;

      /**
       * <code>optional int32 age = 1;</code>
       * 
       * @return Whether the age field is set.
       */
      @java.lang.Override
      public boolean hasAge() {
        return ((bitField0_ & 0x00000001) != 0);
      }

      /**
       * <code>optional int32 age = 1;</code>
       * 
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }

      /**
       * <code>optional int32 age = 1;</code>
       * 
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {

        age_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      /**
       * <code>optional int32 age = 1;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        onChanged();
        return this;
      }

      private int id_;

      /**
       * <code>optional int32 id = 2;</code>
       * 
       * @return Whether the id field is set.
       */
      @java.lang.Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) != 0);
      }

      /**
       * <code>optional int32 id = 2;</code>
       * 
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }

      /**
       * <code>optional int32 id = 2;</code>
       * 
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      /**
       * <code>optional int32 id = 2;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private boolean endTransaction_;

      /**
       * <code>optional bool end_transaction = 3;</code>
       * 
       * @return Whether the endTransaction field is set.
       */
      @java.lang.Override
      public boolean hasEndTransaction() {
        return ((bitField0_ & 0x00000004) != 0);
      }

      /**
       * <code>optional bool end_transaction = 3;</code>
       * 
       * @return The endTransaction.
       */
      @java.lang.Override
      public boolean getEndTransaction() {
        return endTransaction_;
      }

      /**
       * <code>optional bool end_transaction = 3;</code>
       * 
       * @param value The endTransaction to set.
       * @return This builder for chaining.
       */
      public Builder setEndTransaction(boolean value) {

        endTransaction_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      /**
       * <code>optional bool end_transaction = 3;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearEndTransaction() {
        bitField0_ = (bitField0_ & ~0x00000004);
        endTransaction_ = false;
        onChanged();
        return this;
      }

      private long sourceRecordId_;

      /**
       * <code>optional int64 source_record_id = 4;</code>
       * 
       * @return Whether the sourceRecordId field is set.
       */
      @java.lang.Override
      public boolean hasSourceRecordId() {
        return ((bitField0_ & 0x00000008) != 0);
      }

      /**
       * <code>optional int64 source_record_id = 4;</code>
       * 
       * @return The sourceRecordId.
       */
      @java.lang.Override
      public long getSourceRecordId() {
        return sourceRecordId_;
      }

      /**
       * <code>optional int64 source_record_id = 4;</code>
       * 
       * @param value The sourceRecordId to set.
       * @return This builder for chaining.
       */
      public Builder setSourceRecordId(long value) {

        sourceRecordId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      /**
       * <code>optional int64 source_record_id = 4;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearSourceRecordId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sourceRecordId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object serviceFileId_ = "";

      /**
       * <code>optional string service_file_id = 5;</code>
       * 
       * @return Whether the serviceFileId field is set.
       */
      public boolean hasServiceFileId() {
        return ((bitField0_ & 0x00000010) != 0);
      }

      /**
       * <code>optional string service_file_id = 5;</code>
       * 
       * @return The serviceFileId.
       */
      public java.lang.String getServiceFileId() {
        java.lang.Object ref = serviceFileId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serviceFileId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>optional string service_file_id = 5;</code>
       * 
       * @return The bytes for serviceFileId.
       */
      public com.google.protobuf.ByteString getServiceFileIdBytes() {
        java.lang.Object ref = serviceFileId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
          serviceFileId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>optional string service_file_id = 5;</code>
       * 
       * @param value The serviceFileId to set.
       * @return This builder for chaining.
       */
      public Builder setServiceFileId(
          java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        serviceFileId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      /**
       * <code>optional string service_file_id = 5;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearServiceFileId() {
        serviceFileId_ = getDefaultInstance().getServiceFileId();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      /**
       * <code>optional string service_file_id = 5;</code>
       * 
       * @param value The bytes for serviceFileId to set.
       * @return This builder for chaining.
       */
      public Builder setServiceFileIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        serviceFileId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object nameSt_ = "";

      /**
       * <code>optional string name_st = 6;</code>
       * 
       * @return Whether the nameSt field is set.
       */
      public boolean hasNameSt() {
        return ((bitField0_ & 0x00000020) != 0);
      }

      /**
       * <code>optional string name_st = 6;</code>
       * 
       * @return The nameSt.
       */
      public java.lang.String getNameSt() {
        java.lang.Object ref = nameSt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nameSt_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>optional string name_st = 6;</code>
       * 
       * @return The bytes for nameSt.
       */
      public com.google.protobuf.ByteString getNameStBytes() {
        java.lang.Object ref = nameSt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
          nameSt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>optional string name_st = 6;</code>
       * 
       * @param value The nameSt to set.
       * @return This builder for chaining.
       */
      public Builder setNameSt(
          java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        nameSt_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      /**
       * <code>optional string name_st = 6;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearNameSt() {
        nameSt_ = getDefaultInstance().getNameSt();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      /**
       * <code>optional string name_st = 6;</code>
       * 
       * @param value The bytes for nameSt to set.
       * @return This builder for chaining.
       */
      public Builder setNameStBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        nameSt_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:bigquerystorage.Test2)
    }

    // @@protoc_insertion_point(class_scope:bigquerystorage.Test2)
    private static final com.example.bigquerystorage.TestProto2.Test2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.bigquerystorage.TestProto2.Test2();
    }

    public static com.example.bigquerystorage.TestProto2.Test2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated
    public static final com.google.protobuf.Parser<Test2> PARSER = new com.google.protobuf.AbstractParser<Test2>() {
      @java.lang.Override
      public Test2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Test2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Test2> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.bigquerystorage.TestProto2.Test2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor internal_static_bigquerystorage_Test2_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_bigquerystorage_Test2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    java.lang.String[] descriptorData = {
        "\n\013Test2.proto\022\017bigquerystorage\"}\n\005Test2\022" +
            "\013\n\003age\030\001 \001(\005\022\n\n\002id\030\002 \001(\005\022\027\n\017end_transact" +
            "ion\030\003 \001(\010\022\030\n\020source_record_id\030\004 \001(\003\022\027\n\017s" +
            "ervice_file_id\030\005 \001(\t\022\017\n\007name_st\030\006 \001(\tB)\n" +
            "\033com.example.bigquerystorageB\nTestProto2"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
            });
    internal_static_bigquerystorage_Test2_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_bigquerystorage_Test2_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bigquerystorage_Test2_descriptor,
        new java.lang.String[] { "Age", "Id", "EndTransaction", "SourceRecordId", "ServiceFileId", "NameSt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
